# Generated by Django 4.2.14 on 2025-10-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido1', models.CharField(max_length=150)),
                ('apellido2', models.CharField(blank=True, max_length=150)),
                ('nombre1', models.CharField(max_length=150)),
                ('nombre2', models.CharField(blank=True, max_length=150)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Diplomatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('diplomatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='asistencias.diplomatura')),
            ],
            options={
                'unique_together': {('diplomatura', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inicio_habilitacion', models.DateTimeField(help_text='Inicio de ventana para marcar presente')),
                ('fin_habilitacion', models.DateTimeField(help_text='Fin de ventana para marcar presente')),
                ('tema', models.CharField(blank=True, max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='asistencias.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencias.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencias.clase')),
            ],
            options={
                'unique_together': {('clase', 'alumno')},
            },
        ),
    ]
